#!/bin/sh
#
# Start bigeye
#

export QT_QPA_EGLFS_PHYSICAL_WIDTH=211
export QT_QPA_EGLFS_PHYSICAL_HEIGHT=158
export QT_QPA_EGLFS_KMS_CONFIG=/root/sabresd.json

start() {
	printf "Starting skynet-studio: "
	start-stop-daemon -b -S -q -m -p /var/run/skynet-studio.pid --exec /root/skynet-studio
	echo "OK"
}

stop() {
	printf "Stopping skynet-studio: "
	start-stop-daemon -K -q -p /var/run/skynet-studio.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
